openapi: 3.0.3
info:
  title: Games Service
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: kizil@mail.com
  version: 1.0.0
  description: Games Service
servers:
  - url: /
tags:
  - name: games
    description: Games
paths:
  /games:
    get:
      tags:
        - games
      operationId: showAllGames
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\GamesController@showAll'
      summary: Show всех объектов типа Game
      description: Show всех объектов типа Game
      responses:
        "200":
          description: Успешный ответ
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /games/create:
    post:
      tags:
        - games
      operationId: createGame
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\GamesController@create'
      summary: Create объекта типа Game
      description: Create объекта типа Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: './games/games.yaml#/GameCreateRequest'
      responses:
        "201":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './games/games.yaml#/GameResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/ServerError'
  /games/connect:
    post:
      tags:
        - games
      operationId: connectGame
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\GamesController@connect'
      summary: Connect to объект типа Game
      description: Connect to объект типа Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: './games/games.yaml#/GameConnectOrDeleteRequest'
      responses:
        "202":
          description: Успешный ответ
        "401":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /games/destroy:
    post:
      tags:
        - games
      operationId: destroyGame
      x-lg-handler: 'App\Http\ApiV1\Modules\Games\Controllers\GamesController@destroy'
      summary: Destroy объекта типа Game
      description: Destroy объекта типа Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: './games/games.yaml#/GameConnectOrDeleteRequest'
      responses:
        "204":
          description: Успешный ответ
        "400":
          $ref: '#/components/responses/BadRequest'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'

components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
        - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'